### ISSUE TITLE
Update UI to include newly added funds

### ISSUE THREAD

**Issue by MichaelDeBoey** [NexVeridian/ark-invest-api-rust-data#5]
I didn't find the UI repo, hence why I'm posting this request here

**Comment by NexVeridian** [comment]
the redoc rest api repo is here [github.com/NexVeridian/ark-invest-api-rust](https://github.com/NexVeridian/ark-invest-api-rust) and is hosted at [api.NexVeridian.com](https://api.nexveridian.com/)

it should already be updated
https://github.com/NexVeridian/ark-invest-api-rust/commit/793cde6154e5c834ad8e72bfa1a0122691614bf2 and https://github.com/NexVeridian/ark-invest-api-rust/commit/cbc7afad20f62bd2eb0a5ab3511a4ae57c5a888b

**Comment by MichaelDeBoey** [comment]
@NexVeridian I was actually talking about https://nexveridian.com/ARK/ARKK, not the API docs

**Comment by MichaelDeBoey** [comment]
@NexVeridian Would be nice to have the repo publicly available
